config/routes.rb
RicardoTaboada::Application.routes.draw do
    
  get "documents/new"

  get "attachments/new"

  get "users/new"

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :agendas
  resources :documents

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete                   

  match '/about',   to: 'static_pages#about'
  match '/contacts', to: 'static_pages#contacts'
  match '/curriculum', to: 'static_pages#curriculum'  
  match '/projects', to: 'static_pages#projects'
 
  match '/about_alert', to: 'static_pages#about_alert'
  match '/about_internship', to: 'static_pages#about_internship'
  match '/about_ispgaya', to: 'static_pages#about_ispgaya'

  match '/roadmap', to: 'agendas#index'
  match '/documents' , to: 'documents#index'

  root to: 'static_pages#home'

end

app/models/agenda.rb
class Agenda < ActiveRecord::Base
  attr_accessible :end_date, :start_date, :tasks

  validates :start_date, presence:true
  validates :end_date, presence:true
  validates :tasks, presence:true

end

app/models/document.rb
class Document < ActiveRecord::Base
  attr_accessible :doc_type, :file

  has_attached_file :file,
      :storage => :s3,
      :s3_credentials => {
        :bucket => ENV['S3_BUCKET_NAME'],
        :access_key_id => ENV['AWS_ACCESS_KEY_ID'],
        :secret_access_key => ENV['AWS_SECRET_ACCESS_KEY']
      }


  validates :doc_type, presence: true 
  validates :file, presence: true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :text
#  email      :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation
  has_secure_password

  before_save :create_remember_token

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true

  private

    def create_remember_token
      self.remember_token= SecureRandom.urlsafe_base64
    end
end

app/controllers/agendas_controller.rb
class AgendasController < ApplicationController
  before_filter :signed_in_user

  def new
  end

  def create
    @agenda = Agenda.new(params[:agenda])
    if @agenda.save
      redirect_to roadmap_url
    else
      render 'index'
    end
  end

  def show
  end

  def index
    @agenda = Agenda.new
    @agendas = Agenda
  end


  private
    # Method to tes if a user is signed in and redirects it if its not authenticated 
    def signed_in_user
        #Method signed_in? defined in app/helpers/sessions_helper.rb
      redirect_to signin_url, notice: "Please sign in." unless signed_in? #notice :"Please sign in" = flash[:notice] = "Please sign in"
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_filter :signed_in_user

  def new
  end

  def create
    @document = Document.new(params[:document])
    if @document.save
      redirect_to documents_url
    else
      render 'index'
    end

  end

  def index
    @document = Document.new
    @docs = Document
  end

  def destroy
    Document.find_by_id_document(params[:id]).destroy
    flash[:success] = "Document removed."
    redirect_to documents_url 
  end

  private
    # Method to tes if a user is signed in and redirects it if its not authenticated 
    def signed_in_user
        #Method signed_in? defined in app/helpers/sessions_helper.rb
      redirect_to signin_url, notice: "Please sign in." unless signed_in? #notice :"Please sign in" = flash[:notice] = "Please sign in"
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end
  
  def create
    user = User.find_by_email(params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to root_path
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home 	
     out = 'home'    
  end

  def curriculum
     out = 'curriculum'
  end

  def projects
  end

  def about
  end

  def contact
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/agendas_helper.rb
module AgendasHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
# Returns the full title on per page basis.

  def full_title(page_title)
    base_title = "Ricardo Taboada"
    if page_title.empty?
        base_title
    else
        "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end
 
  def signed_in?
    !current_user.nil?
  end
 
  def current_user=(user)
    @current_user = user
  end
 
  def current_user
    @current_user  ||= User.find_by_remember_token(cookies[:remember_token])
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper

  def current_time
      t = Time.now
      m = Date::MONTHNAMES[Date.today.month]
      x = "#{m} #{t.year}"
  end

  def is_active?(page_name)
      "active" if params[:action] == page_name
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/agendas/index.html.erb
<% provide(:title, 'Agenda semanal') %>

  <h1>Agenda semanal</h1>

  <div class="row" id="agenda-insert">
    <div class="span5">

      <%if current_user.email == "ricardo.taboada@hotmail.com" %>
        <%= form_for(@agenda) do |f| %>
            <%# Parcial de gerar erros localizado em app/views/shared/_error_messages_agenda.html.erb %>
          <%= render 'shared/error_messages_agenda' %>

          <%= f.label :start_date %>
          <%= f.text_field :start_date %>

          <%= f.label :end_date %>
          <%= f.text_field :end_date %>

          <%= f.label :tasks %>
          <%= f.text_area :tasks, :cols => "10", :rows => "5" %>

          <%= f.submit "Create", class: "btn btn-large btn-primary" %>
        <%end%>
      <%end%>
    </div>
  </div>

  <div class="container-fluid">
      <div class="row-fluid">
        <div class="span2">
           <p></p>
            <div class="tabbable tabs-left teste">
              <ul class="nav nav-tabs myTab">
                <li class="active"><a href="#tab3" data-toggle="tab">Março</a></li>
                <li><a href="#tab4" data-toggle="tab">Abril</a></li>
                <li><a href="#tab5" data-toggle="tab">Maio</a></li>
                <li><a href="#tab6" data-toggle="tab">Junho</a></li>
                <li><a href="#tab7" data-toggle="tab">Julho</a></li>
              </ul>
            </div>
        </div>

        <div class="span10">
     <p><br></p>

          <div class="tab-content">
            <div class="tab-pane active fade in" id="tab3">
	      <%@agendas.all.each do |a| %>
	        <% if a.start_date.month == 3 %>
                  <li>
                    <p><span class="word_agenda_gray">From: </span>
                    <span class="word_agenda_black"><%= a.start_date.strftime("%d-%m-%Y") %> </span> 
                    <span class="word_agenda_gray">to: </span>
                    <span class="word_agenda_black"> <%= a.end_date.strftime("%d-%m-%Y") %></span></p>
                    <p><span class="word_agenda_black"><%= simple_format h a.tasks %></span></p>
                  </li>
                <%end%>
              <%end%>
            </div>

            <div class="tab-pane fade in" id="tab4">
              <%@agendas.all.each do |a| %>
                <% if a.start_date.month == 4 %>
                  <li>
                    <p><span class="word_agenda_gray">From: </span>
                    <span class="word_agenda_black"><%= a.start_date.strftime("%d-%m-%Y") %> </span>
                    <span class="word_agenda_gray">to: </span>
                    <span class="word_agenda_black"> <%= a.end_date.strftime("%d-%m-%Y") %></span></p>
                    <p><span class="word_agenda_black"><%= simple_format h a.tasks %></span></p>
                  </li>
                <%end%>
              <%end%>
            </div>

            <div class="tab-pane fade in" id="tab5">
              <%@agendas.all.each do |a| %>
                <% if a.start_date.month == 5 %>
                  <li>
                    <p><span class="word_agenda_gray">From: </span>
                    <span class="word_agenda_black"><%= a.start_date.strftime("%d-%m-%Y") %> </span>
                    <span class="word_agenda_gray">to: </span>
                    <span class="word_agenda_black"> <%= a.end_date.strftime("%d-%m-%Y") %></span></p>
                    <p><span class="word_agenda_black"><%= simple_format h a.tasks %></span></p>
                  </li>
                <%end%>
              <%end%>
            </div>

            <div class="tab-pane fade in" id="tab6">
              <%@agendas.all.each do |a| %>
                <% if a.start_date.month == 6 %>
                  <li>
                    <p><span class="word_agenda_gray">From: </span>
                    <span class="word_agenda_black"><%= a.start_date.strftime("%d-%m-%Y") %> </span>
                    <span class="word_agenda_gray">to: </span>
                    <span class="word_agenda_black"> <%= a.end_date.strftime("%d-%m-%Y") %></span></p>
                    <p><span class="word_agenda_black"><%= simple_format h a.tasks %></span></p>
                  </li>
                <%end%>
              <%end%>
            </div>

            <div class="tab-pane fade in" id="tab7">
              <%@agendas.all.each do |a| %>
                <% if a.start_date.month == 7 %>
                  <li>
                    <p><span class="word_agenda_gray">From: </span>
                    <span class="word_agenda_black"><%= a.start_date.strftime("%d-%m-%Y") %> </span>
                    <span class="word_agenda_gray">to: </span>
                    <span class="word_agenda_black"> <%= a.end_date.strftime("%d-%m-%Y") %></span></p>
                    <p><span class="word_agenda_black"><%= simple_format h a.tasks %></span></p>
                  </li>
                <%end%>
              <%end%>
            </div>
          </div>

        </div>
      </div>
  </div>

app/views/agendas/new.html.erb
<h1>Agendas#new</h1>
<p>Find me in app/views/agendas/new.html.erb</p>

app/views/documents/index.html.erb
<% provide(:title, 'Documentos') %>

  <h1>Documentos</h1>


<% if current_user.email == "ricardo.taboada@hotmail.com" %>
  <%= form_for @document, :html => { :multipart => true } do |f| %>
       <%# Parcial de gerar erros localizado em app/views/shared/_error_messages_document.html.erb %>
    <%= render 'shared/error_messages_document' %>

    <%= f.label :doc_type %>
    <%= f.text_field :doc_type %>

    <%= f.file_field :file %>    

    <%= f.submit "Submit", class: "btn btn-large btn-primary"%>
  <%end%>
<%end%>

  <div class="container-fluid">
      <div class="row-fluid">
        <ul class="agendas">
	  <% @docs.all.each do |d| %>
            <li>
              <p>
              <table style="width: 940px">
                <tr>
                  <td style="width: 470px; text-align: left">
                    <i class="icon-file"></i> <%= link_to d.doc_type, d.file.url(:original, false) %> Inserted at: <%= d.updated_at.strftime("%H:%Mh of %d-%m-%Y")%>
                  </td>
                  <td style="text-align: right">
                    <%if current_user.email =="ricardo.taboada@hotmail.com" %>
                      <i class="icon-trash"></i> <%= link_to "Remove", d, method: :delete, data: {confirm: "Are you sure you want to remove the file #{d.doc_type} ?" } %>
		    <%end%>
                  </td>
                </tr>
              </table> 
              </p>
            </li>
          <%end%>
        </ul>
      </div>
    </div>

app/views/documents/new.html.erb
<h1>Documents#new</h1>
<p>Find me in app/views/documents/new.html.erb</p>

app/views/layouts/_footer.html.erb
 <footer class="navbar navbar-bottom" id="footer">
   <div class="container">
    <div class="navbar-inner">
      <div class="container">
        <%#<a href="ricardo.taboada@hotmail.com">2012-2013 Ricardo Taboada</a>%>
        <table class="table-footer" style="width: 940px; margin-top: 10px">
	  <tr>
	    <td style="text-align: left; font-weight:bold">Contacts</td><td style="text-align: right; font-weight: bold">Links</td>
	  </tr>
	</table>
        <p></p>
        <table class="table-footer" style="width: 920px">
	  <tr>
            <td style="text-align: left"><a href="mailto:ricardo.taboada@hotmail.com">@ Email</a></td><td style="text-align: right"><a href="http://www.ispgaya.pt">ISPGaya</a></td>
          </tr>
	  <tr>
            <td style="text-align: left"><img src="/assets/lin.png" alt="lin.png"><a href="http://pt.linkedin.com/in/ricardotaboada"> Linked In</a></td><td style="text-align: right"><a href="http://www.ruby-lang.org">Ruby</a></td>
	  </tr>
	  <tr>
            <td style="text-align: left"><img src="/assets/fb.png" alt="fb.png"><a href="http://www.facebook.com/ricardo.taboada.7"> facebook</a></td><td style="text-align: right"><a href="http://rubyonrails.org">Ruby on Rails</a></td>
          </tr>
	  <tr>
            <td style="text-align: left"><img src="/assets/gh.png" alt="gh.png"><a href="https://github.com/locrian"> GitHub</a></td><td style="text-align: right"><a href=""></a></td>
          </tr>
           <tr>
            <td style="text-align: right"><p></p></td><td></td>
          </tr>

	</table>
      </div>
    </div>
   </div>
  </footer>




    

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <%= link_to "ricardo taboada", root_path , id: "logo" %>
        <nav>
          <ul class="nav pull-right">
		<%# is_active? is a helper method defined in static pages helper and tests for the current active page%>
            <li class="<%= is_active?("home")%>"><%= link_to "Home", root_path, :class => is_active?("Home") %></li>
            <li class="<%= is_active?("curriculum")%>"><%= link_to "Curriculum", curriculum_path %></li>
	    <li class="<%= is_active?("projects")%>"><%= link_to "Projects", projects_path %></li>
	    <li id="navbar_separator"></li>
            <% if signed_in? %>
              <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Documents<b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Documentos", documents_path%></li>
                  <%#<li class="divider"></li>%>
                  <%#<li><%= link_to "Actas", '#' ></li>%>
                  <li class="divider"></li>
                  <li><%= link_to "Diario semanal", roadmap_path%></li>
                </ul>
              </li>

              <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><%#= link_to "Profile", '#' %></li>
                  <li><%#= link_to "Settings", '#' %></li>
                  <!--li class="divider"></li-->
                  <li>
                    <%= link_to "Sign out", signout_path, method: "delete" %>
                  </li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to "Sign in", signin_path %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </div>
  </header>

app/views/layouts/_hero-home.html.erb
<div class="row features" id="home-technologies">
   <br><br>
   <%= link_to image_tag("alert2.png", alt: "Alert"), 'http://www.alert-online.com' %>
   <br>
      <div class="span6">
        <%= link_to image_tag("alert_icon.png", alt: "About ALERT"), about_alert_path %>
           <h3>About ALERT</h3>
      </div>
    
      <div class="span6">
        <%= link_to image_tag("techs.png", alt: "The Internship"), about_internship_path %>
             <h3>The Internship</h3>
      </div>

      <div class="span6">
         <%= link_to image_tag("ispgaya.png", alt: "ISPGaya"), about_ispgaya_path %>
             <h3>About ISPGaya</h3>
      </div>
 </div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <div id="wrap">
    <%= render 'layouts/header' %>
    <%# If this is the home page then the hero unit is out of the container so it can have full width %> 
    <% if is_active?("home") == 'active' %>
      <div class="hero-unit" id ="hu-home">
         <div class="container">
            <%= render 'layouts/hero-home' %>
         </div>
      </div>
    <% end %>
    <%#= yield %>                                          <!--Page body's go here with "yield", comented this in container so it can have full width-->
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>                                                <!-- Page body's go here with "yield"-->
      <%#= render 'layouts/footer' %>
      <%#= debug(params) if Rails.env.development? %>
    </div>
    <div id="push"></div>
  </div>
  <%= render 'layouts/footer' %>
  
</body>
</html>

app/views/shared/_error_messages_agenda.html.erb
<%# Parcial que trata das mensagens de erro ao lidar com a tabela Agenda da base de dados %>

<% if @agenda.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@agenda.errors.count, "error") %>.
    </div>
    <ul>
    <% @agenda.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_error_messages_document.html.erb
<%# Parcial que trata das mensagens de erro ao lidar com a tabela Document da base de dados %>

<% if @document.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@document.errors.count, "error") %>.
    </div>
    <ul>
    <% @document.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/about_alert.html.erb
<% provide(:title, 'About ALERT Life Sciences Computing') %>

  <h1>ALERT Life Sciences Computing, S.A.</h1>

  <div class="container-fluid">
    <div class="row-fluid">
      <ul class="alert_info">
        <table style="width: 940px">
	  <tr>
	    <td style="width: 500px">
		<p class="alert_info_text">
Formerly known as MNI - Médicos Na Internet, ALERT Life Sciences Computing, S.A. is the parent company of the ALERT Group. It is entirely dedicated to the development, distribution and implementation of ALERT® clinical software to create paper-free clinical environments.</p>

<p class="alert_info_text">Based in Porto, the parent company started its activity in December 1999. It currently has a multidisciplinary team that includes physicians, designers, architects, engineers, mathematicians and managers.</p>

<p class="alert_info_text">ALERT Life Sciences Computing, S.A. is a privately owned company.</p>

<p class="alert_info_text">With a turnover above 42.6 million Euros in 2009, ALERT has reported a significant increase in sales every year. This increase results from the company's high investment in developing and commercializing quality products.</p>

<p class="alert_info_text">ALERT Life Sciences Computing, S.A. integrates COTEC's innovative SME network and the company's training methodology was selected by the European Social Fund to integrate two publications that exemplify success stories.</p>

<p class="alert_info_text">The company is a HIMSS (Healthcare Information and Management Systems Society) Platinum Corporate Member and has been taking part in the IHE (Integrating the Healthcare Enterprise) initiatives. ALERT® has obtained several interoperability certifications.</p>
	      </p>	
            </td>
	    <td style="width: 440px">
                <img style="margin-bottom: 40px" src="/assets/alert_logo_info_page.jpg"/>
 		
		<img src="/assets/alert_building.png"/>
                <p style="font-size: 10px; text-align: center"> ALERT Life Sciences Computing, S.A. Vila Nova de Gaia Offices</p>
            </td>
          </tr>
	</table> 
      </ul>
    </div>
  </div>

app/views/static_pages/about_internship.html.erb
<% provide(:title, 'The Internship') %>

  <h1>The Internship</h1>

  <div class="container-fluid">
    <div class="row-fluid">
      <ul class="alert_info">
        <table style="width: 940px">
          <tr>
            <td style="width: 500px">
                <p class="alert_info_text">
		 The project proposed by ALERT has its INTER-ALERT® product as the main target.
The INTER-ALERT is a software developed by ALERT and plays the function of an Enterprise Service Bus, but only in  environments where one or more ALERT products are implemented. So INTER-ALERT® plays a central role in a clinical environment with where ALERT solutions are implemented, ensuring that any clinical informantion with its origin from or to ALERT software is allways delivered to its destiny. 
                </p>     
		<p class="alert_info_text">
Being INTER-ALERT® a core product on ALERT strategy, the project proposed consists in two main topics, develop a module to manage the data comunication channels used by INTER-ALERT® and other module to analyse the performance of the message handling done by INTER-ALERT®.
		</p> 
		<p class="alert_info_text">

This will provide tools to ALERT support teams, so they can manage comunications channels and do message monitoring in a more efficient way that what is being done now. 
		</p>
            </td>
            <td style="width: 440px">
                <img style="margin-bottom: 40px" src="/assets/alert_logo_info_page.jpg"/>
                <p style="text-align: center; font-size: 50px">
			INTER-ALERT®
		</p>   
            </td>
          </tr>
        </table> 
      </ul>
    </div>
  </div>

app/views/static_pages/about_ispgaya.html.erb
<% provide(:title, 'ISPGaya') %>

  <h1>ISPGaya</h1>

  <div class="container-fluid">
    <div class="row-fluid">
      <ul class="alert_info">
        <table style="width: 940px">
          <tr>
            <td style="width: 500px">
                <p class="alert_info_text">
	          ISPGaya is a Superior Polytechnic Institute situated in Vila Nova de Gaia, which promotes several study plans, from Engineering courses to Social Service courses.
Currently ISPGaya has to offer to its students 13 courses with Licentiate degree and 8 courses with a Masters degree.
		</p>
<p class="alert_info_text" style="font-weight:bold">
Licentiate degree courses:<br>
</p>
<p class="alert_info_text">
- Electronic and Automation Engeneering<br>
- Computer Sciences Engineering<br>
- Mechanical Engineering<br>
- Industrial Management Engineering<br>
- Telecomunications and Computers Engineering<br>
- Renovable Energies Engineering<br>
- Computer Sciences for Managment<br>
- Accounting and Management<br>
- Management<br>
</p>
<p class="alert_info_text">
- Public Administration<br>
- Tourism<br>
- Social Service<br>
</p>
<p class="alert_info_text">
- Basic Education<br>
</p>

<p class="alert_info_text" style="font-weight: bold">
Masters degree courses:<br>
</p>
<p class="alert_info_text">
- Pré-scholar Education<br>
- Network Administration and Computer Systems<br>
- Energy Management and Energetic Efficiency<br>
- Social Educative Intervention<br>
- Pré-scholar Education and Teaching 1st Cycle of Basic Education<br>
</p>
<p class="alert_info_text">
- Social Service<br>
- Social Gerontology<br>
- Human resources and Organizational Behaviour<br>
                </p>
            </td>
            <td style="width: 440px">
                <img style="margin-bottom: 40px" src="/assets/ispgaya_big.png"/>
		<img src="/assets/ispgaya.jpg"/>
                <p style="text-align: center">
                        ISPGaya Building
                </p>  
            </td>
          </tr>
        </table> 
      </ul>
    </div>
  </div>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/contacts.html.erb
<% provide(:title, 'Contacts') %>
<div class="center hero-unit">
  <h1>Here are my contacts</h1>
</div>

app/views/static_pages/home.html.erb
<% provide(:title, '') %>
   
   
 

  

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>